@host = http://localhost:8080

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImNyYWlnZGVudG9uMkBob3RtYWlsLmNvbSIsIkZpcnN0TmFtZSI6IkNyYWlnMTIiLCJMYXN0TmFtZSI6IkRlbnRvbjEyIiwiUm9sZSI6IlVTRVIiLCJVc2VySWQiOiI2OWExZTY2M2UyOTQwOGRlNzk1YTFjYWYiLCJpc3MiOiJNYWdpY1N0cmVhbSIsImV4cCI6MTc3MjMxMDQ5MCwiaWF0IjoxNzcyMjI0MDkwfQ.fGWIBBNJqzCJhkSO6GU18jdYUekjTPgybMLtJ7-m4QE
POST {{host}}/addmovie
Content-Type:  application/json
Authorization: Bearer {{token}}

{
        "imdb_id": "tt0102034",
        "title": "Highlander 2: The Quickening",
        "poster_path": "https://image.tmdb.org/t/p/original/gFPIgpwtnsiq6AG5HlgOzK1TNke.jpg",
        "youtube_id": "pRgJVvoihCQ",
        "genre": [
            {
                "genre_id": 6,
                "genre_name": "Sci-fi"
            },
            {
                "genre_id": 4,
                "genre_name": "Fantasy"
            }
        ],
        "admin_review": "This movie was really bad",
        "ranking": {
            "ranking_value": 4,
            "ranking_name": "Bad"
        }
    }