@host = http://localhost:8080

POST {{host}}/register
Content-Type:  application/json

{
  "first_name": "Craig12",
  "last_name": "Denton12",
  "email": "craigdenton2@hotmail.com",
  "password": "Password12!",
  "role": "USER",
  "token": "",
  "refresh_token": "",
  "favourite_genres": [
    {
      "genre_id": 1,
      "genre_name": "Comedy"
    },
    {
      "genre_id": 5,
      "genre_name": "Thriller"
    },
    {
      "genre_id": 6,
      "genre_name": "Sci-Fi"
    }
  ]
}